import { library } from '@fortawesome/fontawesome-svg-core';
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome';

// Import icons you need
import { 
    faSignOutAlt,
    faUser,
    faLock,
    faCamera,
    faAward,
    faStar,
    faFire,
    faCalendarCheck,
    faHeart,
    faCheckCircle,
    faTrophy,
    faPlus,
    faBookOpen,
    faChevronRight,
    faChevronLeft,
    faSignInAlt,
    faGear,
    faMinus,
    faSearch,
    faSun,
    faMoon,
    faEnvelope,
    faGlobe,
    faHome,
    faCalculator,
    faCreditCard,
    faBitcoinSign,
    faDonate,
    faBookmark,
    faCheck,
    faTimes,
    faInfoCircle,
    faRedo,
    faCode,
    faCodeBranch,
    faBug,
    faLightbulb,
    faBook,
    faBookQuran,
    faLanguage,
    faHandHoldingHeart,
    faExclamationCircle,
    faComments,
    faEdit,
    faHand,
    faArrowRight,
    faLink,
    faNewspaper,
    faCalendarAlt,
    faUserPen,
    faTrash,
    faPencil,
    faPenToSquare,
    faEye,
    faEyeSlash
} from '@fortawesome/free-solid-svg-icons';

// Import brand icons
import {
    faTelegram,
    faInstagram,
    faGithub,
    faFacebook,
    faTwitter,
    faWhatsapp,
} from '@fortawesome/free-brands-svg-icons';

// Add icons to library
library.add(
    faSignOutAlt,
    faUser,
    faLock,
    faCamera,
    faAward,
    faStar,
    faFire,
    faCalendarCheck,
    faHeart,
    faCheckCircle,
    faTrophy,
    faPlus,
    faBookOpen,
    faChevronRight,
    faChevronLeft,
    faSignInAlt,
    faGear,
    faMinus,
    faSearch,
    faSun,
    faMoon,
    faEnvelope,
    faGlobe,
    faHome,
    faCalculator,
    faCreditCard,
    faBitcoinSign,
    faTelegram,
    faInstagram,
    faGithub,
    faDonate,
    faBookmark,
    faCheck,
    faTimes,
    faInfoCircle,
    faRedo,
    faCode,
    faCodeBranch,
    faBug,
    faLightbulb,
    faBook,
    faBookQuran,
    faLanguage,
    faHandHoldingHeart,
    faExclamationCircle,
    faComments,
    faEdit,
    faHand,
    faFacebook,
    faTwitter,
    faWhatsapp,
    faArrowRight,
    faLink,
    faNewspaper,
    faCalendarAlt,
    faUserPen,
    faTrash,
    faPencil,
    faPenToSquare,
    faEye,
    faEyeSlash
);

export default FontAwesomeIcon; 